/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package states;

/**
 *
 * @author DARVISH KISHOR
 */
public class UttarPradesh extends javax.swing.JFrame {

    /**
     * Creates new form UttarPradesh
     */
    public UttarPradesh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CandidateIcon = new javax.swing.JLabel();
        VoterIcon = new javax.swing.JLabel();
        ResultsIcon = new javax.swing.JLabel();
        ElectionIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Election Management System");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 270, 430, 44);

        CandidateIcon.setBackground(new java.awt.Color(255, 102, 102));
        CandidateIcon.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        CandidateIcon.setForeground(new java.awt.Color(255, 51, 102));
        CandidateIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\DARVISH KISHOR\\Videos\\Candidate.jpg")); // NOI18N
        CandidateIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 1, true));
        CandidateIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CandidateIconMouseClicked(evt);
            }
        });
        jPanel1.add(CandidateIcon);
        CandidateIcon.setBounds(10, 170, 172, 138);

        VoterIcon.setBackground(new java.awt.Color(255, 102, 102));
        VoterIcon.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        VoterIcon.setForeground(new java.awt.Color(255, 51, 102));
        VoterIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\DARVISH KISHOR\\Videos\\Voters.jpg")); // NOI18N
        VoterIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        VoterIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoterIconMouseClicked(evt);
            }
        });
        jPanel1.add(VoterIcon);
        VoterIcon.setBounds(600, 0, 175, 138);

        ResultsIcon.setBackground(new java.awt.Color(255, 102, 102));
        ResultsIcon.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        ResultsIcon.setForeground(new java.awt.Color(255, 51, 102));
        ResultsIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\DARVISH KISHOR\\Videos\\Results.jpg")); // NOI18N
        ResultsIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        ResultsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultsIconMouseClicked(evt);
            }
        });
        jPanel1.add(ResultsIcon);
        ResultsIcon.setBounds(600, 170, 175, 138);

        ElectionIcon.setBackground(new java.awt.Color(255, 102, 102));
        ElectionIcon.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        ElectionIcon.setForeground(new java.awt.Color(255, 51, 102));
        ElectionIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\DARVISH KISHOR\\Videos\\Election.jpg")); // NOI18N
        ElectionIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true));
        ElectionIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElectionIconMouseClicked(evt);
            }
        });
        jPanel1.add(ElectionIcon);
        ElectionIcon.setBounds(10, 10, 170, 130);

        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("ELECTION");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 140, 90, 20);

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("VOTER");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(660, 140, 60, 20);

        jLabel7.setBackground(new java.awt.Color(255, 51, 51));
        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("CANDIDATE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 310, 110, 20);

        jLabel8.setBackground(new java.awt.Color(255, 51, 51));
        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("RESULTS");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(660, 310, 80, 20);

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Uttar Pradesh");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 10, 200, 44);

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setForeground(new java.awt.Color(255, 51, 255));

        Back.setIcon(new javax.swing.ImageIcon("C:\\Users\\DARVISH KISHOR\\Videos\\Back.png")); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(730, Short.MAX_VALUE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 342, 784, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DARVISH KISHOR\\Videos\\Chunaw.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CandidateIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CandidateIconMouseClicked
        new electionmanagementsystem.CandidatePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CandidateIconMouseClicked

    private void VoterIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoterIconMouseClicked
        new electionmanagementsystem.Voters().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoterIconMouseClicked

    private void ResultsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultsIconMouseClicked
        new electionmanagementsystem.DashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResultsIconMouseClicked

    private void ElectionIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElectionIconMouseClicked
        new electionmanagementsystem.Election().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ElectionIconMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new electionmanagementsystem.login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UttarPradesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UttarPradesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UttarPradesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UttarPradesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UttarPradesh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel CandidateIcon;
    private javax.swing.JLabel ElectionIcon;
    private javax.swing.JLabel ResultsIcon;
    private javax.swing.JLabel VoterIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
